# Site settings
title: Ruiqi Chen
email: ruiqi.chen@vub.be
description: "
  Department of Electronics and Informatics (ETRO)<br>
  Vrije Universiteit Brussel (VUB)<br>
  1050 Elsene, Brussels, Belgium"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

google_scholar: "https://scholar.google.com/citations?user=XXXX"
orcid: "https://orcid.org/XXXX"
researchgate: "https://www.researchgate.net/profile/XXXX"

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: 
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""